### ISSUE TITLE
[TESTING] remove testbed sync-server in favor of flagd v0.9.1+

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd-testbed#114]
flagd itself [now implements the sync.proto](https://github.com/open-feature/flagd/pull/1237). This means the sync-server in this repo (only used for testing) can be replaced with flagd itself.

- [x] update https://github.com/open-feature/flagd-testbed/blob/main/sync/Dockerfile and https://github.com/open-feature/flagd-testbed/blob/main/sync/Dockerfile.unstable to make use of flagd instead of the small implementation [here](https://github.com/open-feature/flagd-testbed/tree/main/sync/pkg)
- [x] delete https://github.com/open-feature/flagd-testbed/tree/main/sync/pkg

**Comment by aepfli** [comment]
do we actually need the sync docker files? seems like https://github.com/open-feature/flagd-testbed/blob/main/flagd/Dockerfile is already doing what we want. i think we can delete the sync folder, or am i wrong here. side question, do we need to somehow deprecate some artefacts? or are they somewhere used?

**Comment by toddbaert** [comment]
I think you're right @aepfli , we don't need another Dockerfile or image. I think we just need to expose a new port!

**Comment by aepfli** [comment]
i started removing the sync server 

- https://github.com/open-feature/js-sdk-contrib/pull/1100
