### ISSUE TITLE
Add tests for configuration nuances and misconfugurations

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd-testbed#84]
We should add some flags [here](https://github.com/open-feature/flagd-testbed/tree/main/flags) and associated tests [here](https://github.com/open-feature/flagd-testbed/blob/main/gherkin/flagd.feature) for common edge cases and mis-configurations, including:

- targeting rule returns `null` should fall through to `defaultVariant` and return reason `STATIC`
- invalid/erroneous JSON logic (should error, and cause use of application (SDK) default)
- targeting returns a variant which is not in variant definition (should error, and cause use of application (SDK)  default)

**Comment by beeme1mr** [comment]
We should add a test that ensures an invalid semantic version is handled consistently and one that tests the handling of non-string responses from the targeting rule.
